# Generated by Django 5.0.3 on 2025-11-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_jobdescription_options_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
