# Generated by Django 5.0.3 on 2025-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_increase_file_type_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
